spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
# jwt.secret=${JWT_SECRET:seknna-dev-secret-min-256-bits-change-in-prod}
jwt.expiration=900000
jwt.refresh-expiration=604800000

# Logging
logging.level.org.springframework=INFO
logging.level.app=DEBUG
logging.file.name=logs/app.log

# Actuator
management.endpoint.health.show-details=always
management.health.db.enabled=true

# spring.autoconfigure.exclude=\
#   org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
#   org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration,\
#   org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
spring.security.user.name=admin
spring.security.user.password=admin


# jwt.secret=fjzeSO6QwgzGcFJCX0fMTD1kuTaQrZc5tLcKCtYAwqE=
# jwt.expiration=86400000